services:
  app:
    build: .
    ports:
      - 50051:50051
    environment:
      - DB_HOST=db
      - DB_PORT=27017
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis

  db:
    image: mongo:latest
    ports:
      - 27017:27017

  redis:
    image: redis:latest
    ports:
      - 6379:6379